### ISSUE TITLE
Avoid possible namespaces conflicts 

### ISSUE THREAD

**Issue by mhor** [sinergi/php-browser-detector#11]
Current namespace can cause namespace conflicts. A  valid namespace should starting by the vendor name.

Source: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md#mandatory

**Comment by ve3** [comment]
Yep, I agree.
To begins with just \Browser is too wide and may conflict with others that use just \Browser too.
If it is begin with your name, for example: \Gabrielbull\Browser might be better.
:)

**Comment by gabrielbull** [comment]
Fixed with release 5.0.0. New namespace is `Sinergi\BrowserDetector`

**Comment by ve3** [comment]
Wow! You are very active developer. I like that!
Thanks a lot. 👍 :+1:
