### ISSUE TITLE
You should unite with https://github.com/serbanghita/Mobile-Detect

### ISSUE THREAD

**Issue by Vashkatsi** [sinergi/php-browser-detector#44]
It would be much better tool. That's all I wanted to say.

**Comment by vinkla** [comment]
Why?

**Comment by Vashkatsi** [comment]
Because with that lib you can detect more mobile devices

**Comment by vinkla** [comment]
Okay, do you know which ones? Maybe we could add them here.

**Comment by ThaDafinser** [comment]
@Vashkatsi there are a lot of UserAgent parsers around. `Mobile-Detect` is just one of them.
https://github.com/ThaDafinser/UserAgentParser

By the way: In the current stable version `Mobile-Detect` is only useable for mobile detection, but not for Browser/OS or Device analysis.

**Comment by gabrielbull** [comment]
Will close because this is not a real issue.
