### ISSUE TITLE
5.0.2: Device Detection does not work?

### ISSUE THREAD

**Issue by ThaDafinser** [sinergi/php-browser-detector#46]
Hello!

while implementing your provider here: https://github.com/ThaDafinser/UserAgentParser/pull/20
i could not find a valid UA to get iPad or iPhone as the device name.

Is there maybe a bug?

**Comment by ThaDafinser** [comment]
@gabrielbull now i know why it does not work.

`Device` does not have __construct() method https://github.com/sinergi/php-browser-detector/blob/master/src/Device.php

But the documentation mention it should be used like this:
https://github.com/sinergi/php-browser-detector#usage-2

**Comment by gabrielbull** [comment]
This is fixed now with release 5.1.0. Thanks!

**Comment by ThaDafinser** [comment]
Thank you for the fast pach :smile: 

I will update it asap

**Comment by ThaDafinser** [comment]
@gabrielbull works good. See example here: http://useragent.mkf.solutions/
