### ISSUE TITLE
Should not throw Exception, when could not detect browser

### ISSUE THREAD

**Issue by DMGPage** [sinergi/php-browser-detector#48]
I found problem that, if this script can't find some information about browser, it throw Exception. Instead, it should return information, that it found and false or null, if something not found, but not Exception. To test this, I used this chrome plugin: https://chrome.google.com/webstore/detail/random-hide-user-agent/einpaelgookohagofgnnkcfjbkkgepnp. Set User Agent to "Chrome" and this script will return:
Undefined offset: 1 in ../vendor/gabrielbull/browser/src/Browser/BrowserDetector.php:280

**Comment by gabrielbull** [comment]
This should be fixed with Release 5.1.1, let me know if it is not.
