### ISSUE TITLE
Chrome OS detected as OS X

### ISSUE THREAD

**Issue by pavarnos** [sinergi/php-browser-detector#51]
Mozilla/5.0 (X11; CrOS x86_64 7520.62.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36

is detected as 
Chrome 47 OS X
because OSDetector::checkOSX() is seeing the "OS x" of "CrOS x86_64"

(thanks for the useful package btw)

**Comment by gabrielbull** [comment]
Thanks for letting me know, I pushed a new release with a fix for Chrome OS. Cheers!

:+1:
