### ISSUE TITLE
Test suite - where are the user agents?

### ISSUE THREAD

**Issue by ThaDafinser** [sinergi/php-browser-detector#59]
Hello,

i'm currently searching for the user agent tests

I just found one here https://github.com/sinergi/php-browser-detector/blob/master/tests/BrowserDetector/Tests/_files/UserAgentStrings.xml

Where are the others?

**Comment by gabrielbull** [comment]
You're right, they were accidentally deleted 😶. I have restored the file to a previous commit.

Thanks! 🎈🎉
