### ISSUE TITLE
Detecting IE in Compatibility Mode

### ISSUE THREAD

**Issue by coreywynsma** [sinergi/php-browser-detector#60]
Wondering if BrowserDetector::checkBrowserInternetExplorer() would benefit from a mechanism to detect IE's true version when in compatibility mode. I believe if the user agent string contains the combination of strings below, the true version at hand can determined. Of course, it's not a simple as just returning the actual version, as IE11 in compatibility mode renders pages more akin to 7, for instance, but some mechanism by which to determine both the actual version and compatibility mode would be quite useful. Thank you for all the hard work on what is really a very nice package!

MSIE 7.0 && Trident/7.0 is IE11 in compatibility mode
MSIE 7.0 && Trident/6.0 is IE10 in compatibility mode
MSIE 7.0 && Trident/5.0 is IE9 in compatibility mode
MSIE 7.0 && Trident/4.0 is IE8 in compatibility mode

**Comment by gabrielbull** [comment]
This sounds like a good idea. The Browser class could have additional methods like `isCompatibilityMode` and `getCompatibilityModeVersion`. Do you have time for a PR?

**Comment by coreywynsma** [comment]
I'll take a stab at a compatibility_mode feature branch and will do a PR when I have something. Thanks again!

**Comment by coreywynsma** [comment]
This issue has been resolved via PR https://github.com/sinergi/php-browser-detector/pull/61
