### ISSUE TITLE
Detect Facebook and Twitter browsers

### ISSUE THREAD

**Issue by vinkla** [sinergi/php-browser-detector#63]
Since websites more often are opened in webviews in both the Facebook and Twitter applications on numerous different types of devices it would be nice to detect if the user currently are using the Facebook application etc. I know we can detect Facebook with `FBAN`. Not sure about Twitter though. Any ideas?

**Comment by gabrielbull** [comment]
Here's some I found here: https://mobiforge.com/research-analysis/webviews-and-user-agent-strings

## Android

### Facebook
`
Mozilla/5.0 (Linux; Android 4.4.4; One Build/KTU84L.H4) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/28.0.0.20.16;]
`

### Twitter
`
Mozilla/5.0 (Linux; Android 4.4.4; One Build/KTU84L.H4) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36
`

### Standard Chrome
`
Mozilla/5.0 (Linux; Android 4.4.4; One Build/KTU84L.H4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.135 Mobile Safari/537.36
`

## iOS

### Facebook
`
Mozilla/5.0 (iPhone; CPU iPhone OS 8_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12D508 [FBAN/FBIOS;FBAV/27.0.0.10.12;FBBV/8291884;FBDV/iPhone7,1;FBMD/iPhone;FBSN/iPhone OS;FBSV/8.2;FBSS/3; FBCR/vodafoneIE;FBID/phone;FBLC/en_US;FBOP/5]
`

### Twitter
`
Mozilla/5.0 (iPhone; CPU iPhone OS 8_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12D508
`

### Tweetbot
`
Mozilla/5.0 (iPhone; CPU iPhone OS 8_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12D508
`

### Standard Safari
`
Mozilla/5.0 (iPhone; CPU iPhone OS 8_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12D508
`

**Comment by vinkla** [comment]
@gabrielbull :+1:

**Comment by gabrielbull** [comment]
With that in mind, it seems pretty hard to detect a webview if not explicitly specified. There would be no harm in adding web view detection for Facebook by adding new methods to the browser class. For instance `isFacebookWebview`.

**Comment by vinkla** [comment]
Yeah, maybe we should search for `FBAV` since that occurs on both iOS and Android.
