### ISSUE TITLE
Can't detect Windows Phone

### ISSUE THREAD

**Issue by gloern13** [sinergi/php-browser-detector#67]
Detects Windows Phone like chrome OS and in checkWindowsPhone missed $os->setIsMobile(true);
user-agent example: "Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1; Microsoft; Lumia 640 LTE) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Mobile Safari/537.36 Edge/14.14393"

**Comment by gabrielbull** [comment]
Hey! Thanks for reporting. I have published a new version containing the fix. Cheers! 🍾
