### ISSUE TITLE
Detects wrong wversion for BackBerry 

### ISSUE THREAD

**Issue by izumeroot** [sinergi/php-browser-detector#69]
I get UserAgent from here https://www.whatismybrowser.com/developers/tools/user-agent-parser/browse/view/blackberry-browser--105

> UserAgent: Mozilla/5.0 (BlackBerry; U; BlackBerry 9380; en) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.1.0.523 Mobile Safari/534.11+

I try:
`echo $browser->getName().'#'.$browser->getVersion()`

And get:

> BlackBerry#534.11+

But correct version is 7.1.0.523

Thank you

**Comment by gabrielbull** [comment]
Thanks for reporting the problem. I published a fix for it!
