### ISSUE TITLE
SamsungBrowser

### ISSUE THREAD

**Issue by halukpp** [sinergi/php-browser-detector#72]
The stock browser used by new Samsung Androids is significantly different compared to both Chrome and old android stock browsers. One important difference for instance, is that Samsung Browser does not support browser notifications (among other important differences.)  I think it would be good if the library would not show this browser as Chrome.

**Comment by gabrielbull** [comment]
Can you provide the user agent string? Most of them can be found here: http://www.useragentstring.com/pages/useragentstring.php, otherwise it is fairly easy to extract if you have access to a samsung android browser.

**Comment by halukpp** [comment]
Here is a sample user agent: 
`Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-G360T1 Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.3 Chrome/38.0.2125.102 Mobile Safari/537.36
`

Here are more samples: http://www.webapps-online.com/online-tools/user-agent-strings/dv/browser643083/samsung-browser

Thank you.

**Comment by gabrielbull** [comment]
Thanks! Added it in new release. 🎉
