### ISSUE TITLE
Wkhtmltopdf detection

### ISSUE THREAD

**Issue by zendre4** [sinergi/php-browser-detector#73]
Hello,

I don't now if it's possible, but I need a browser detector for detect wkhtmltopdf. 
For information wkhtmltopdf is a software for print a web page into a PDF.

Thanks

**Comment by zendre4** [comment]
http://wkhtmltopdf.org/

**Comment by gabrielbull** [comment]
@zendre4 I'm sure this is possible, but first, you need to extract the user agent string from __wkhtmltopdf__. To do so, you could create a test page that would print the user agent string when visiting, this way, you could create a PDF of that test page using __wkhtmltopdf__. Here is the code to print the user agent string:

```php
<?php

$useragent = $_SERVER['HTTP_USER_AGENT'];
echo $useragent;

```

**Comment by zendre4** [comment]
Thanks for the rapidity of the response !

The user agent is :

```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) wkhtmltopdf-amd64 Safari/534.34
28.12.2016
```

**Comment by gabrielbull** [comment]
done with Release 6.1.2. 🎉

**Comment by zendre4** [comment]
Thanks a lot!!!
