### ISSUE TITLE
 Class 'Sinergi\BrowserDetector\Browser' not found

### ISSUE THREAD

**Issue by marlowmedia** [sinergi/php-browser-detector#74]
Hey,

This is just what iv been looking for, how ever im having an issue installing/running it as i get the error:

> Class 'Sinergi\BrowserDetector\Browser' not found

I installed it via Compser whilst in the public_html folder via SSH. During the install the end part of the install outputted this:

> symfony/polyfill-mbstring suggests installing ext-mbstring (For best performance)
> symfony/console suggests installing symfony/process ()
> symfony/event-dispatcher suggests installing symfony/dependency-injection ()
> symfony/event-dispatcher suggests installing symfony/http-kernel ()
> guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)
> satooshi/php-coveralls suggests installing symfony/http-kernel (Allows Symfony integration)
> sebastian/global-state suggests installing ext-uopz (*)
> phpunit/phpunit-mock-objects suggests installing ext-soap (*)
> phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.1)
> phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
> Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
> Writing lock file
> Generating autoload files

As you can see it says somthing about guzzle, so has it been installed or not? Any help would be great please, i have root access to the server.

Thank you!

**Comment by gabrielbull** [comment]
This library does not use guzzle. Have you included the autoload file generated by composer?

**Comment by marlowmedia** [comment]
Thanks for the quick response, how do you mean have i included the autoload file?

**Comment by gabrielbull** [comment]
When you install with composer, it creates a `vendor` directory in your project. In this `vendor` directory there is an autoload file that needs to be included before you can use libraries installed through composer. Something like this:

```php
require __DIR__ . '/vendor/autoload.php';

// ... the rest of your code
```

You can find more information on composer's website: https://getcomposer.org/doc/01-basic-usage.md
