### ISSUE TITLE
New Edge(Chromium) detected as Chrome

### ISSUE THREAD

**Issue by zeyser** [sinergi/php-browser-detector#94]
New UA string in Edge:
`"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.66 Safari/537.36 Edg/80.0.361.40"`
Do you plan to detect such case as Edge?

**Comment by gabrielbull** [comment]
@zeyser I am no longer involved in this library. If you want to add it I can add you as a contributor. Let me know.

**Comment by oooMiRooo** [comment]
@zeyser Are you planing to add this new Edge UA?

**Comment by jonasschumacher** [comment]
@gabrielbull I could do that

**Comment by gabrielbull** [comment]
Hi @jonasschumacher, if you are interested in becoming a maintainer of this library, please shoot me an email at me@gabrielbull.com

**Comment by jonasschumacher** [comment]
@gabrielbull I'm sorry, I just wanted to submit the PR. I forgot I had to fork the repo first.
